name: Deploy to live

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Archive production artifact
        uses: actions/upload-artifact@v2
        with:
          name: portfolio-artifact
          path: ./

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download the artifact
        uses: actions/download-artifact@v2
        with:
          name: portfolio-artifact
          path: ./

      - name: Sync files to hosting
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./
          server-dir: /testwpupload
