name: Deploy to live

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare artifact
        run: |
          mkdir -p artifact
          rsync -av --exclude='artifact' --exclude='.git' ./ artifact/

      - name: Archive production artifact
        uses: actions/upload-artifact@v2
        with:
          name: portfolio-artifact
          path: artifact/

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download the artifact
        uses: actions/download-artifact@v2
        with:
          name: portfolio-artifact
          path: ./artifact

      - name: Sync files to hosting
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./artifact/
          server-dir: /dev
