name: Deploy to live

on:
  push:
      branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Determine if code files changed
        id: changes
        run: |
          if git diff --quiet HEAD^ HEAD ./path/to/code/files; then
            echo "no_changes=true" >> $GITHUB_ENV
          else
            echo "no_changes=false" >> $GITHUB_ENV
          fi

      - name: Cache artifact
        id: cache-artifact
        if: env.no_changes == 'true'
        uses: actions/cache@v3
        with:
          path: artifact
          key: ${{ runner.os }}-artifact-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-artifact-

      - name: Prepare artifact
        if: env.no_changes != 'true'
        run: |
          mkdir -p artifact
          rsync -av --exclude='artifact' --exclude='.git' ./ artifact/

      - name: Archive production artifact
        if: env.no_changes != 'true'
        uses: actions/upload-artifact@v2
        with:
          name: portfolio-artifact
          path: artifact/

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download the artifact
        uses: actions/download-artifact@v2
        with:
          name: portfolio-artifact
          path: ./artifact

      - name: Sync files to hosting
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./artifact/
          server-dir: /dev/
